server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fourteam?useSSL=false
    username: root
    password: a
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update